language: php

php:
 - '7.0'
 - '7.1'
 - '7.2'

before_script:
 - composer install
 - mkdir tests/logs

script:
 - phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
 